### ISSUE TITLE
TypeError: value.apply is not a function

### ISSUE THREAD

**Issue by vaibhavmule** [dbushong/async-q#6]
```

  at Promise.apply (/home/username/project_name/node_modules/async-q/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/home/username/project_name/node_modules/async-q/node_modules/q/q.js:741:41)
    at /home/username/project_name/async-q/node_modules/q/q.js:1304:14
    at flush (/home/username/project_name/node_modules/async-q/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13) 


```

I'm getting error, when I'm doing to use method called `async.parallel`

**Comment by dbushong** [comment]
Please see if 0.3.1 solves your problems, if not, please share your code

**Comment by vaibhavmule** [comment]
I need to mention, it was not working even on 0.2.2 that's why we have use each for now. 

https://github.com/Mindgreppers/OHHDL/blob/dev/backend/app/utils/resolveJoins.js#L15 

and 

https://github.com/Mindgreppers/OHHDL/blob/dev/backend/app/utils/resolveJoins.js#L33

**Comment by dbushong** [comment]
Erm, can you give an example of how you were actually calling `async.parallel`?  BTW, as [the docs](https://github.com/dbushong/async-q#parallel) note, `async.parallel` isn't actually all that useful; it pretty much does the same thing as `Q.all()`...

**Comment by dbushong** [comment]
closing due to inactivity
